### ISSUE TITLE
Update the library to support the v2 API

### ISSUE THREAD

**Issue by hillelcoren** [fotografde/omnipay-checkoutcom#1]
When trying to use this library we see the following error:

`You tried to access the endpoint with an invalid method`

From reviewing the code it looks like this library uses v1 of the API however the docs now refer to v2. 

http://developers.checkout.com/docs/browser/quickstart/browser-integration

Are there any plans to update the library?

**Comment by beinbm** [comment]
Hi hillelcore,

we're already using v2. 
The endpoints are defined here:
https://github.com/fotografde/omnipay-checkoutcom/blob/master/src/Message/AbstractRequest.php#L28-L29

When does the error occure? Maybe I can help you with the integration

**Comment by hillelcoren** [comment]
@beinbm Thanks for offering to help!

I was trying to use their [Card Tokenisation](http://developers.checkout.com/docs/browser/quickstart/checkoutkit-js/card-tokenisation) approach. I was seeing that error when calling completePurchase with the token set as the transactionReference.

**Comment by beinbm** [comment]
I think there is a missing step here.
We do completePurchase() with the cko-cc-paymenToken
I dont know if its possible with the cko-card-token in your case.

**Comment by hillelcoren** [comment]
Thanks, that's helpful. I'll switch back to using Checkout.js instead of CheckoutKit.js.
